In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import GradientBoostingClassifier
import xgboost as xgb

C:\Users\nrgurram\Anaconda3\lib\site-packages\sklearn\cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)

In [2]:
input_data = pd.read_csv("train.csv", index_col="ID")
input_data.head()

,age,sex,chest,resting_blood_pressure,serum_cholestoral,fasting_blood_sugar,resting_electrocardiographic_results,maximum_heart_rate_achieved,exercise_induced_angina,oldpeak,slope,number_of_major_vessels,thal,class
ID,,,,,,,,,,,,,,
0,49.207124,0,4.000000,162.996167,181.108682,0,0,148.227858,1,0.944547,2,0,3,1
1,53.628425,1,1.741596,130.233730,276.474630,0,2,152.917139,0,0.119070,2,0,3,0
2,49.591426,1,4.000000,146.999012,223.300517,1,2,102.352090,1,1.616747,2,2,7,1
3,58.991445,1,4.000000,112.369143,187.245501,0,0,158.164750,1,0.000000,1,1,7,1
4,51.053602,1,1.954609,138.032047,238.482868,0,0,172.540828,0,1.150464,1,1,3,0

In [3]:
test_samples = pd.read_csv("test.csv", index_col="ID")
test_samples.head()

,age,sex,chest,resting_blood_pressure,serum_cholestoral,fasting_blood_sugar,resting_electrocardiographic_results,maximum_heart_rate_achieved,exercise_induced_angina,oldpeak,slope,number_of_major_vessels,thal
ID,,,,,,,,,,,,,
600000,53.963191,1,4.000000,136.940829,236.862814,0,2,143.961525,1,0.711100,1,2,7
600001,49.621479,1,4.000000,122.024651,226.593019,0,2,112.220874,1,0.000000,1,1,7
600002,36.933893,1,1.300924,127.585643,351.061046,0,0,177.945922,0,0.313078,1,0,7
600003,54.884588,1,3.000000,124.876745,250.370530,0,0,153.176526,0,0.308277,1,1,7
600004,71.016392,0,1.746972,120.922600,210.979710,0,0,164.573122,0,1.021370,1,1,3

In [4]:
input_features = input_data.iloc[:,:-1].values
input_classes = input_data.iloc[:,-1].values

(train_samples, val_samples, train_classes, val_classes) = \
train_test_split(input_features, input_classes, test_size=0.2, stratify=input_classes, random_state=0)

In [5]:
def predict_accuracy(model):
    print(model.best_params_, model.best_score_)
    predict_classes = model.predict(val_samples)
    print("Accuracy : %0.4f" % accuracy_score(val_classes, predict_classes))

In [ ]:
grid_parameters = {'n_estimators':range(130,150,10)}
grid_xgb = GridSearchCV(xgb.XGBClassifier(max_depth=4),  grid_parameters, cv=3, n_jobs=-1)
grid_xgb.fit(train_samples, train_classes)

In [ ]:
predict_accuracy(grid_xgb)

In [ ]:
grid_parameters = {"learning_rate": [0.2, 0.3, 0.4, 0.5]}
grid_xgb = GridSearchCV(xgb.XGBClassifier(max_depth=4, n_estimators=140),  grid_parameters, cv=3, n_jobs=-1)
grid_xgb.fit(train_samples, train_classes)

In [ ]:
predict_accuracy(grid_xgb)

In [ ]:
grid_parameters = {'min_child_weight':range(1,6,1), 'max_depth':range(1,4,1), 'gamma' : [i/10.0 for i in range(0,5)]}
grid_xgb = GridSearchCV(xgb.XGBClassifier(n_estimators=140, learning_rate=0.3),  grid_parameters, cv=3, n_jobs=-1)
grid_xgb.fit(train_samples, train_classes)

In [ ]:
predict_accuracy(grid_xgb)

In [ ]:
grid_parameters = {'gamma' : [i/10.0 for i in range(0,5)]}
grid_xgb = GridSearchCV(xgb.XGBClassifier(n_estimators=140, learning_rate=0.3, \
                                          min_child_weight=, max_depth=4), \
                        grid_parameters, cv=3, n_jobs=-1)
grid_xgb.fit(train_samples, train_classes)

In [ ]:
predict_accuracy(grid_xgb)

In [ ]:
xgb_tree = xgb.XGBClassifier(n_estimators=130, subsample=0.5)
xgb_tree.fit(train_samples, train_classes)

In [ ]:
predict_accuracy(xgb_tree)